import { Transaction } from '../types/finance';

/**
 * Generates a high-resolution canvas receipt card for a transaction
 * and triggers a PNG download or native image file share.
 */
export const exportTransactionAsImage = async (
  txn: Transaction,
  accountName: string,
  categoryName: string,
  appName: string = 'Couple Ledger'
): Promise<void> => {
  const canvas = document.createElement('canvas');
  const scale = 2; // High DPI resolution
  const width = 600 * scale;
  const height = 420 * scale;
  canvas.width = width;
  canvas.height = height;

  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  // Background Gradient Card
  const isExpense = txn.TransactionType === 'Expense';
  const isIncome = txn.TransactionType === 'Income';
  const accentColor = isExpense ? '#f43f5e' : isIncome ? '#10b981' : '#0284c7';

  // Card Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  // Outer Rounded Border
  ctx.strokeStyle = '#e2e8f0';
  ctx.lineWidth = 4;
  ctx.strokeRect(10, 10, width - 20, height - 20);

  // Header Banner Accent
  const headerGradient = ctx.createLinearGradient(0, 0, width, 0);
  headerGradient.addColorStop(0, accentColor);
  headerGradient.addColorStop(1, '#0d9488'); // Teal blend
  ctx.fillStyle = headerGradient;
  ctx.fillRect(10, 10, width - 20, 24 * scale);

  // App Name & Receipt Label
  ctx.fillStyle = '#ffffff';
  ctx.font = `bold ${14 * scale}px sans-serif`;
  ctx.fillText(appName.toUpperCase(), 24 * scale, 26 * scale);

  ctx.font = `${11 * scale}px sans-serif`;
  ctx.textAlign = 'right';
  ctx.fillText('TRANSACTION RECEIPT', width - (24 * scale), 26 * scale);

  ctx.textAlign = 'left';

  // Body content offset
  const startY = 65 * scale;

  // Transaction ID & Date
  ctx.fillStyle = '#64748b';
  ctx.font = `${12 * scale}px sans-serif`;
  ctx.fillText(`ID: ${txn.TransactionID}`, 30 * scale, startY);
  ctx.textAlign = 'right';
  ctx.fillText(`Date: ${txn.Date} ${txn.Time || ''}`, width - (30 * scale), startY);
  ctx.textAlign = 'left';

  // Divider Line
  ctx.strokeStyle = '#f1f5f9';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(30 * scale, startY + (12 * scale));
  ctx.lineTo(width - (30 * scale), startY + (12 * scale));
  ctx.stroke();

  // Amount Block
  const amountY = startY + (50 * scale);
  ctx.fillStyle = '#0f172a';
  ctx.font = `bold ${12 * scale}px sans-serif`;
  ctx.fillText('AMOUNT', 30 * scale, amountY - (22 * scale));

  const formattedAmount = `${txn.Currency} ${txn.Amount.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
  ctx.fillStyle = accentColor;
  ctx.font = `bold ${28 * scale}px sans-serif`;
  ctx.fillText(formattedAmount, 30 * scale, amountY + (10 * scale));

  // Type Pill
  ctx.fillStyle = isExpense ? '#ffe4e6' : isIncome ? '#d1fae5' : '#e0f2fe';
  const pillWidth = 110 * scale;
  const pillHeight = 28 * scale;
  const pillX = width - (30 * scale) - pillWidth;
  const pillY = amountY - (15 * scale);
  
  ctx.beginPath();
  ctx.roundRect(pillX, pillY, pillWidth, pillHeight, 14 * scale);
  ctx.fill();

  ctx.fillStyle = accentColor;
  ctx.font = `bold ${12 * scale}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.fillText(txn.TransactionType.toUpperCase(), pillX + (pillWidth / 2), pillY + (18 * scale));
  ctx.textAlign = 'left';

  // Details Grid
  const detailsY = amountY + (55 * scale);

  // Description
  ctx.fillStyle = '#64748b';
  ctx.font = `${11 * scale}px sans-serif`;
  ctx.fillText('DESCRIPTION', 30 * scale, detailsY);

  ctx.fillStyle = '#1e293b';
  ctx.font = `bold ${13 * scale}px sans-serif`;
  ctx.fillText(txn.Description || 'N/A', 30 * scale, detailsY + (18 * scale));

  // Category
  ctx.fillStyle = '#64748b';
  ctx.font = `${11 * scale}px sans-serif`;
  ctx.fillText('CATEGORY', 320 * scale, detailsY);

  ctx.fillStyle = '#1e293b';
  ctx.font = `bold ${13 * scale}px sans-serif`;
  ctx.fillText(categoryName, 320 * scale, detailsY + (18 * scale));

  // Second Details Row
  const row2Y = detailsY + (48 * scale);

  // Account
  ctx.fillStyle = '#64748b';
  ctx.font = `${11 * scale}px sans-serif`;
  ctx.fillText('ACCOUNT', 30 * scale, row2Y);

  ctx.fillStyle = '#1e293b';
  ctx.font = `bold ${13 * scale}px sans-serif`;
  ctx.fillText(accountName, 30 * scale, row2Y + (18 * scale));

  // Status & Ownership
  ctx.fillStyle = '#64748b';
  ctx.font = `${11 * scale}px sans-serif`;
  ctx.fillText('CLASSIFICATION', 320 * scale, row2Y);

  ctx.fillStyle = '#1e293b';
  ctx.font = `bold ${13 * scale}px sans-serif`;
  ctx.fillText(`${txn.OwnershipType} | ${txn.Status}`, 320 * scale, row2Y + (18 * scale));

  // Footer Watermark
  const footerY = height - (30 * scale);
  ctx.fillStyle = '#94a3b8';
  ctx.font = `${10 * scale}px sans-serif`;
  ctx.fillText(`Generated by ${appName} • ${new Date().toLocaleDateString()}`, 30 * scale, footerY);

  // Export as Image file
  const dataUrl = canvas.toDataURL('image/png');
  const fileName = `Transaction-${txn.TransactionID}.png`;

  // Check if Web Share API supports sharing files directly
  if (navigator.share && navigator.canShare) {
    try {
      const blob = await (await fetch(dataUrl)).blob();
      const file = new File([blob], fileName, { type: 'image/png' });

      if (navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `Transaction Receipt - ${txn.Description}`,
          text: `Transaction summary for ${txn.Description}: ${formattedAmount}`,
        });
        return;
      }
    } catch {
      // Fallback to standard download below
    }
  }

  // Standard Image File Download Fallback
  const link = document.createElement('a');
  link.download = fileName;
  link.href = dataUrl;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
